"""add llm model to device

Revision ID: 27dbe00023d1
Revises: e072274bb492
Create Date: 2026-09-02 15:11:19.801813

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "27dbe00023d1"
down_revision: Union[str, Sequence[str], None] = "e072274bb492"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "device",
        sa.Column(
            "llm_model",
            sa.String(length=128),
            nullable=True,
            comment="设备使用的火山方舟模型 ID；为空时使用系统默认模型",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("device", "llm_model")
    # ### end Alembic commands ###
