"""add conversation summary table

Revision ID: 3f37b85fd962
Revises: d168183e0891
Create Date: 2026-08-26 11:00:17.648039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f37b85fd962'
down_revision: Union[str, Sequence[str], None] = 'd168183e0891'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_summary',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='摘要主键 ID'),
    sa.Column('conversation_id', sa.BigInteger(), nullable=False, comment='所属会话 ID'),
    sa.Column('device_id', sa.BigInteger(), nullable=False, comment='所属设备 ID'),
    sa.Column('summary_text', sa.Text(), nullable=False, comment='摘要正文'),
    sa.Column('covered_start_message_id', sa.BigInteger(), nullable=False, comment='摘要覆盖的起始消息 ID'),
    sa.Column('covered_end_message_id', sa.BigInteger(), nullable=False, comment='摘要覆盖的结束消息 ID'),
    sa.Column('summary_level', sa.String(length=20), server_default=sa.text("'segment'"), nullable=False, comment='摘要级别：segment 分段摘要，aggregate 合并摘要'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False, comment='摘要状态：active 有效，archived 已归档'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='AI 对话历史摘要表'
    )
    op.create_index(op.f('ix_conversation_summary_conversation_id'), 'conversation_summary', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_summary_covered_end_message_id'), 'conversation_summary', ['covered_end_message_id'], unique=False)
    op.create_index(op.f('ix_conversation_summary_device_id'), 'conversation_summary', ['device_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_summary_device_id'), table_name='conversation_summary')
    op.drop_index(op.f('ix_conversation_summary_covered_end_message_id'), table_name='conversation_summary')
    op.drop_index(op.f('ix_conversation_summary_conversation_id'), table_name='conversation_summary')
    op.drop_table('conversation_summary')
    # ### end Alembic commands ###
