"""add device and user_device tables

Revision ID: 7fd910c85f8b
Revises: dabe051ea9e0
Create Date: 2026-08-14 11:10:04.112996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fd910c85f8b'
down_revision: Union[str, Sequence[str], None] = 'dabe051ea9e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='设备主键 ID'),
    sa.Column('device_sn', sa.String(length=64), nullable=False, comment='设备唯一编号'),
    sa.Column('product_key', sa.String(length=64), nullable=False, comment='产品型号或产品系列标识'),
    sa.Column('firmware_version', sa.String(length=32), nullable=True, comment='固件版本'),
    sa.Column('hardware_version', sa.String(length=32), nullable=True, comment='硬件版本'),
    sa.Column('device_secret_hash', sa.String(length=255), nullable=True, comment='设备访问密钥摘要，不保存原始密钥'),
    sa.Column('secret_version', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='设备密钥版本'),
    sa.Column('secret_updated_time', sa.DateTime(), nullable=True, comment='设备密钥最后更新时间'),
    sa.Column('status', sa.SmallInteger(), server_default=sa.text('1'), nullable=False, comment='设备状态：1 正常，0 禁用'),
    sa.Column('last_online_time', sa.DateTime(), nullable=True, comment='最近一次上线时间'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='逻辑删除：0 未删除，1 已删除'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_device_sn'), 'device', ['device_sn'], unique=True)
    op.create_table('user_device',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='绑定关系主键 ID'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户 ID'),
    sa.Column('device_id', sa.BigInteger(), nullable=False, comment='设备 ID'),
    sa.Column('alias', sa.String(length=100), nullable=True, comment='用户设置的设备名称'),
    sa.Column('role', sa.String(length=20), server_default=sa.text("'owner'"), nullable=False, comment='用户对设备的角色：owner 或 member'),
    sa.Column('bind_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='绑定时间'),
    sa.Column('unbind_time', sa.DateTime(), nullable=True, comment='解绑时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='逻辑删除：0 未删除，1 已删除'),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'device_id', name='uq_user_device'),
    comment='用户与设备绑定关系表'
    )
    op.create_index(op.f('ix_user_device_device_id'), 'user_device', ['device_id'], unique=False)
    op.create_index(op.f('ix_user_device_user_id'), 'user_device', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_device_user_id'), table_name='user_device')
    op.drop_index(op.f('ix_user_device_device_id'), table_name='user_device')
    op.drop_table('user_device')
    op.drop_index(op.f('ix_device_device_sn'), table_name='device')
    op.drop_table('device')
    # ### end Alembic commands ###
