"""add llm model to device

Revision ID: c444727a743e
Revises: 27dbe00023d1
Create Date: 2026-09-02 16:58:48.594310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c444727a743e'
down_revision: Union[str, Sequence[str], None] = '27dbe00023d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('model_key', sa.String(length=128), nullable=True, comment='设备选择的模型标识，例如 doubao、qwen、deepseek'))
    op.drop_column('device', 'llm_model')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('llm_model', sa.VARCHAR(length=128), autoincrement=False, nullable=True, comment='设备使用的火山方舟模型 ID；为空时使用系统默认模型'))
    op.drop_column('device', 'model_key')
    # ### end Alembic commands ###
