"""create_postgresql_initial_schema

Revision ID: e072274bb492
Revises:
Create Date: 2026-08-27 17:28:14.440530

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e072274bb492"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversation",
        sa.Column(
            "id",
            sa.BigInteger(),
            autoincrement=True,
            nullable=False,
            comment="会话主键 ID",
        ),
        sa.Column(
            "user_id",
            sa.BigInteger(),
            nullable=True,
            comment="所属用户 ID；设备认证完成前可为空",
        ),
        sa.Column(
            "device_id",
            sa.BigInteger(),
            nullable=True,
            comment="发起对话的设备 ID；设备认证完成前可为空",
        ),
        sa.Column(
            "title",
            sa.String(length=100),
            nullable=True,
            comment="会话标题；第一版可暂不生成",
        ),
        sa.Column(
            "summary",
            sa.Text(),
            nullable=True,
            comment="已压缩的历史对话摘要；第一版暂不使用",
        ),
        sa.Column(
            "message_count",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
            comment="会话消息总数",
        ),
        sa.Column(
            "last_message_at",
            sa.DateTime(),
            nullable=True,
            comment="最后一条消息创建时间",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="会话创建时间",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="会话最后更新时间",
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="AI 对话会话表",
    )
    op.create_index(
        op.f("ix_conversation_device_id"), "conversation", ["device_id"], unique=False
    )
    op.create_index(
        op.f("ix_conversation_user_id"), "conversation", ["user_id"], unique=False
    )
    op.create_table(
        "conversation_message",
        sa.Column(
            "id",
            sa.BigInteger(),
            autoincrement=True,
            nullable=False,
            comment="消息主键 ID",
        ),
        sa.Column(
            "conversation_id", sa.BigInteger(), nullable=False, comment="所属会话 ID"
        ),
        sa.Column(
            "role",
            sa.String(length=20),
            nullable=False,
            comment="消息角色：user 用户，assistant AI 助手",
        ),
        sa.Column(
            "content",
            sa.Text(),
            nullable=False,
            comment="消息文本内容；语音场景中为 STT 识别结果或 AI 回复",
        ),
        sa.Column(
            "source",
            sa.String(length=20),
            server_default=sa.text("'voice'"),
            nullable=False,
            comment="消息来源：voice 语音，text 文字，system 系统",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="消息创建时间",
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="AI 对话消息表",
    )
    op.create_index(
        op.f("ix_conversation_message_conversation_id"),
        "conversation_message",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversation_message_created_at"),
        "conversation_message",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "conversation_summary",
        sa.Column(
            "id",
            sa.BigInteger(),
            autoincrement=True,
            nullable=False,
            comment="摘要主键 ID",
        ),
        sa.Column(
            "conversation_id", sa.BigInteger(), nullable=False, comment="所属会话 ID"
        ),
        sa.Column("device_id", sa.BigInteger(), nullable=False, comment="所属设备 ID"),
        sa.Column("summary_text", sa.Text(), nullable=False, comment="摘要正文"),
        sa.Column(
            "covered_start_message_id",
            sa.BigInteger(),
            nullable=False,
            comment="摘要覆盖的起始消息 ID",
        ),
        sa.Column(
            "covered_end_message_id",
            sa.BigInteger(),
            nullable=False,
            comment="摘要覆盖的结束消息 ID",
        ),
        sa.Column(
            "summary_level",
            sa.String(length=20),
            server_default=sa.text("'segment'"),
            nullable=False,
            comment="摘要级别：segment 分段摘要，aggregate 合并摘要",
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default=sa.text("'active'"),
            nullable=False,
            comment="摘要状态：active 有效，archived 已归档",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="更新时间",
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="AI 对话历史摘要表",
    )
    op.create_index(
        op.f("ix_conversation_summary_conversation_id"),
        "conversation_summary",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversation_summary_covered_end_message_id"),
        "conversation_summary",
        ["covered_end_message_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversation_summary_device_id"),
        "conversation_summary",
        ["device_id"],
        unique=False,
    )
    op.create_table(
        "device",
        sa.Column(
            "id",
            sa.BigInteger(),
            autoincrement=True,
            nullable=False,
            comment="设备主键 ID",
        ),
        sa.Column(
            "device_sn", sa.String(length=64), nullable=False, comment="设备唯一编号"
        ),
        sa.Column(
            "product_key",
            sa.String(length=64),
            nullable=False,
            comment="产品型号或产品系列标识",
        ),
        sa.Column(
            "firmware_version", sa.String(length=32), nullable=True, comment="固件版本"
        ),
        sa.Column(
            "hardware_version", sa.String(length=32), nullable=True, comment="硬件版本"
        ),
        sa.Column(
            "device_secret_hash",
            sa.String(length=255),
            nullable=True,
            comment="设备访问密钥摘要，不保存原始密钥",
        ),
        sa.Column(
            "secret_version",
            sa.Integer(),
            server_default=sa.text("1"),
            nullable=False,
            comment="设备密钥版本",
        ),
        sa.Column(
            "secret_updated_time",
            sa.DateTime(),
            nullable=True,
            comment="设备密钥最后更新时间",
        ),
        sa.Column(
            "status",
            sa.SmallInteger(),
            server_default=sa.text("1"),
            nullable=False,
            comment="设备状态：1 正常，0 禁用",
        ),
        sa.Column(
            "last_online_time", sa.DateTime(), nullable=True, comment="最近一次上线时间"
        ),
        sa.Column(
            "create_time",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column(
            "update_time",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="更新时间",
        ),
        sa.Column(
            "deleted",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
            comment="逻辑删除：0 未删除，1 已删除",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_device_device_sn"), "device", ["device_sn"], unique=True)
    op.create_table(
        "user",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("openid", sa.String(length=64), nullable=False),
        sa.Column("nickname", sa.String(length=100), nullable=True),
        sa.Column("avatar", sa.String(length=500), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("gender", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("birthday", sa.Date(), nullable=True),
        sa.Column("ip_location", sa.String(length=50), nullable=True),
        sa.Column(
            "create_time",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "update_time",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_openid"), "user", ["openid"], unique=True)
    op.create_table(
        "user_device",
        sa.Column(
            "id",
            sa.BigInteger(),
            autoincrement=True,
            nullable=False,
            comment="绑定关系主键 ID",
        ),
        sa.Column("user_id", sa.BigInteger(), nullable=False, comment="用户 ID"),
        sa.Column("device_id", sa.BigInteger(), nullable=False, comment="设备 ID"),
        sa.Column(
            "alias", sa.String(length=100), nullable=True, comment="用户设置的设备名称"
        ),
        sa.Column(
            "role",
            sa.String(length=20),
            server_default=sa.text("'owner'"),
            nullable=False,
            comment="用户对设备的角色：owner 或 member",
        ),
        sa.Column(
            "bind_time",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="绑定时间",
        ),
        sa.Column("unbind_time", sa.DateTime(), nullable=True, comment="解绑时间"),
        sa.Column(
            "update_time",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="更新时间",
        ),
        sa.Column(
            "deleted",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
            comment="逻辑删除：0 未删除，1 已删除",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "device_id", name="uq_user_device"),
        comment="用户与设备绑定关系表",
    )
    op.create_index(
        op.f("ix_user_device_device_id"), "user_device", ["device_id"], unique=False
    )
    op.create_index(
        op.f("ix_user_device_user_id"), "user_device", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_device_user_id"), table_name="user_device")
    op.drop_index(op.f("ix_user_device_device_id"), table_name="user_device")
    op.drop_table("user_device")
    op.drop_index(op.f("ix_user_openid"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_device_device_sn"), table_name="device")
    op.drop_table("device")
    op.drop_index(
        op.f("ix_conversation_summary_device_id"), table_name="conversation_summary"
    )
    op.drop_index(
        op.f("ix_conversation_summary_covered_end_message_id"),
        table_name="conversation_summary",
    )
    op.drop_index(
        op.f("ix_conversation_summary_conversation_id"),
        table_name="conversation_summary",
    )
    op.drop_table("conversation_summary")
    op.drop_index(
        op.f("ix_conversation_message_created_at"), table_name="conversation_message"
    )
    op.drop_index(
        op.f("ix_conversation_message_conversation_id"),
        table_name="conversation_message",
    )
    op.drop_table("conversation_message")
    op.drop_index(op.f("ix_conversation_user_id"), table_name="conversation")
    op.drop_index(op.f("ix_conversation_device_id"), table_name="conversation")
    op.drop_table("conversation")
    # ### end Alembic commands ###
