"""add agent table and device active_agent_id

Revision ID: fac5acb33a67
Revises: 4163d1935929
Create Date: 2026-09-07 09:55:30.775745

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fac5acb33a67'
down_revision: Union[str, Sequence[str], None] = '4163d1935929'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent',
                    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Agent ID'),
                    sa.Column('user_id', sa.BigInteger(), nullable=True,
                              comment='所属用户 ID；系统模板（is_system=True）为 NULL'),
                    sa.Column('name', sa.String(length=32), server_default=sa.text("'小梦'"), nullable=False,
                              comment='agent_name'),
                    sa.Column('system_prompt', sa.String(length=500), nullable=True,
                              comment='用户可编辑的人设，限 500 字'),
                    sa.Column('model_key', sa.String(length=32), server_default=sa.text("'doubao'"), nullable=False,
                              comment='默认 doubao，必须在 MODEL_REGISTRY 内'),
                    sa.Column('voice', sa.String(length=32), server_default=sa.text("'female_gentle'"), nullable=False,
                              comment='默认 female_gentle，存中立别名真实映射在后端'),
                    sa.Column('is_system', sa.Boolean(), server_default=sa.text('false'), nullable=False,
                              comment='默认 False，系统模板为 True'),
                    sa.Column('source_agent_id', sa.BigInteger(), nullable=True, comment='fork 自哪个模板'),
                    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False,
                              comment='创建时间'),
                    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False,
                              comment='更新时间'),
                    sa.Column('deleted', sa.Integer(), server_default=sa.text('0'), nullable=False,
                              comment='逻辑删除：0 未删除，1 已删除'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_agent_user_id'), 'agent', ['user_id'], unique=False)
    op  # 1) 先加可空列
    op.add_column('conversation', sa.Column('session_id', sa.String(length=36), nullable=True,
                                            comment='对外会话 ID（UUID）；预留扩展口，老数据迁移时也填 UUID'))
    # 2) 给已有老行回填随机 UUID（PG13+ 内置 gen_random_uuid）
    op.execute("UPDATE conversation SET session_id = gen_random_uuid()::text WHERE session_id IS NULL")
    # 3) 数据齐了再收紧为 NOT NULL
    op.alter_column('conversation', 'session_id', nullable=False)
    op.add_column('conversation', sa.Column('agent_id', sa.BigInteger(), nullable=True, comment='agent id'))
    op.create_unique_constraint('uq_conversation_agent_session', 'conversation', ['agent_id', 'session_id'])
    op.create_table_comment(
        'conversation',
        'Ai对话表',
        existing_comment='AI 对话会话表',
        schema=None
    )
    op.add_column('conversation_summary', sa.Column('agent_id', sa.BigInteger(), nullable=True, comment='agent id'))
    op.add_column('device', sa.Column('active_agent_id', sa.BigInteger(), nullable=True,
                                      comment='当前激活的智能体，空则回落系统默认'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'active_agent_id')
    op.drop_column('conversation_summary', 'agent_id')
    op.create_table_comment(
        'conversation',
        'AI 对话会话表',
        existing_comment='Ai对话表',
        schema=None
    )
    op.drop_constraint('uq_conversation_agent_session', 'conversation', type_='unique')
    op.drop_column('conversation', 'agent_id')
    op.drop_column('conversation', 'session_id')
    op.drop_index(op.f('ix_agent_user_id'), table_name='agent')
    op.drop_table('agent')
    # ### end Alembic commands ###
