"""add conversation tables

Revision ID: d168183e0891
Revises: 7fd910c85f8b
Create Date: 2026-08-25 15:58:10.452770

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d168183e0891"
down_revision: Union[str, Sequence[str], None] = "7fd910c85f8b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversation",
        sa.Column(
            "id",
            sa.BigInteger(),
            autoincrement=True,
            nullable=False,
            comment="会话主键 ID",
        ),
        sa.Column(
            "user_id",
            sa.BigInteger(),
            nullable=True,
            comment="所属用户 ID；设备认证完成前可为空",
        ),
        sa.Column(
            "device_id",
            sa.BigInteger(),
            nullable=True,
            comment="发起对话的设备 ID；设备认证完成前可为空",
        ),
        sa.Column(
            "title",
            sa.String(length=100),
            nullable=True,
            comment="会话标题；第一版可暂不生成",
        ),
        sa.Column(
            "summary",
            sa.Text(),
            nullable=True,
            comment="已压缩的历史对话摘要；第一版暂不使用",
        ),
        sa.Column(
            "message_count",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
            comment="会话消息总数",
        ),
        sa.Column(
            "last_message_at",
            sa.DateTime(),
            nullable=True,
            comment="最后一条消息创建时间",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="会话创建时间",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="会话最后更新时间",
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="AI 对话会话表",
    )
    op.create_index(
        op.f("ix_conversation_device_id"), "conversation", ["device_id"], unique=False
    )
    op.create_index(
        op.f("ix_conversation_user_id"), "conversation", ["user_id"], unique=False
    )
    op.create_table(
        "conversation_message",
        sa.Column(
            "id",
            sa.BigInteger(),
            autoincrement=True,
            nullable=False,
            comment="消息主键 ID",
        ),
        sa.Column(
            "conversation_id", sa.BigInteger(), nullable=False, comment="所属会话 ID"
        ),
        sa.Column(
            "role",
            sa.String(length=20),
            nullable=False,
            comment="消息角色：user 用户，assistant AI 助手",
        ),
        sa.Column(
            "content",
            sa.Text(),
            nullable=False,
            comment="消息文本内容；语音场景中为 STT 识别结果或 AI 回复",
        ),
        sa.Column(
            "source",
            sa.String(length=20),
            server_default=sa.text("'voice'"),
            nullable=False,
            comment="消息来源：voice 语音，text 文字，system 系统",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="消息创建时间",
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="AI 对话消息表",
    )
    op.create_index(
        op.f("ix_conversation_message_conversation_id"),
        "conversation_message",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversation_message_created_at"),
        "conversation_message",
        ["created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_conversation_message_created_at"), table_name="conversation_message"
    )
    op.drop_index(
        op.f("ix_conversation_message_conversation_id"),
        table_name="conversation_message",
    )
    op.drop_table("conversation_message")
    op.drop_index(op.f("ix_conversation_user_id"), table_name="conversation")
    op.drop_index(op.f("ix_conversation_device_id"), table_name="conversation")
    op.drop_table("conversation")
    # ### end Alembic commands ###
