"""add_birthday_and_ip_location_to_user

Revision ID: dabe051ea9e0
Revises: a1b2c3d4e5f6
Create Date: 2026-08-13 17:34:38.156500

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dabe051ea9e0"
down_revision: str | Sequence[str] | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("birthday", sa.Date(), nullable=True))
    op.add_column("user", sa.Column("ip_location", sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "ip_location")
    op.drop_column("user", "birthday")
    # ### end Alembic commands ###
