"""update user table

Revision ID: ff2e29580cfb
Revises: f1752740ea8b
Create Date: 2026-08-12 10:33:58.508343

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "ff2e29580cfb"
down_revision: str | Sequence[str] | None = "f1752740ea8b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("openid", sa.String(length=64), nullable=False))
    op.add_column("user", sa.Column("nickname", sa.String(length=100), nullable=True))
    op.add_column("user", sa.Column("avatar", sa.String(length=500), nullable=True))
    op.add_column("user", sa.Column("phone", sa.String(length=20), nullable=True))
    op.add_column(
        "user",
        sa.Column(
            "create_time",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "update_time",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "user",
        sa.Column("deleted", sa.Integer(), server_default=sa.text("0"), nullable=False),
    )
    op.alter_column(
        "user",
        "id",
        existing_type=mysql.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.create_index(op.f("ix_user_openid"), "user", ["openid"], unique=True)
    op.drop_column("user", "username")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "username",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=50),
            nullable=False,
        ),
    )
    op.drop_index(op.f("ix_user_openid"), table_name="user")
    op.alter_column(
        "user",
        "id",
        existing_type=sa.BigInteger(),
        type_=mysql.INTEGER(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_column("user", "deleted")
    op.drop_column("user", "update_time")
    op.drop_column("user", "create_time")
    op.drop_column("user", "phone")
    op.drop_column("user", "avatar")
    op.drop_column("user", "nickname")
    op.drop_column("user", "openid")
    # ### end Alembic commands ###
